//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiteSPPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUCHE_PEINTURE
    {
        public int Identifiant { get; set; }
        public string Min { get; set; }
        public string Max { get; set; }
        public string Moy { get; set; }
        public Nullable<int> IdentifiantCouche { get; set; }
        public Nullable<int> IdentifiantPeinture { get; set; }
    
        public virtual COUCHE COUCHE { get; set; }
        public virtual PEINTURE PEINTURE { get; set; }
    }
}
