//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiteSPPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECHANTILLON
    {
        public ECHANTILLON()
        {
            this.RESULTAT_TEST = new HashSet<RESULTAT_TEST>();
        }
    
        public int Identifiant { get; set; }
        public string NumLot { get; set; }
        public Nullable<System.DateTime> DatePeinture { get; set; }
        public Nullable<int> IdentifiantProduit { get; set; }
    
        public virtual PRODUIT PRODUIT { get; set; }
        public virtual ICollection<RESULTAT_TEST> RESULTAT_TEST { get; set; }
    }
}
