//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiteSPPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEINTURE
    {
        public PEINTURE()
        {
            this.COUCHE_PEINTURE = new HashSet<COUCHE_PEINTURE>();
            this.PRODUITs = new HashSet<PRODUIT>();
        }
    
        public int Identifiant { get; set; }
        public string Reference { get; set; }
        public Nullable<byte> BN { get; set; }
        public Nullable<byte> RV { get; set; }
        public Nullable<byte> JB { get; set; }
    
        public virtual ICollection<COUCHE_PEINTURE> COUCHE_PEINTURE { get; set; }
        public virtual ICollection<PRODUIT> PRODUITs { get; set; }
    }
}
