//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiteSPPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIECE
    {
        public PIECE()
        {
            this.PIECE_TEST = new HashSet<PIECE_TEST>();
            this.PRODUITs = new HashSet<PRODUIT>();
        }
    
        public int Identifiant { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> IdentifiantClient { get; set; }
        public Nullable<int> IdentifiantVehicule { get; set; }
        public Nullable<int> IdentifiantType { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual ICollection<PIECE_TEST> PIECE_TEST { get; set; }
        public virtual TYPE TYPE { get; set; }
        public virtual VEHICULE VEHICULE { get; set; }
        public virtual ICollection<PRODUIT> PRODUITs { get; set; }
    }
}
