//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiteSPPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIECE_TEST
    {
        public int Identifiant { get; set; }
        public int IdentifiantPiece { get; set; }
        public int IdentifiantTest { get; set; }
        public string min { get; set; }
        public string max { get; set; }
        public string moy { get; set; }
    
        public virtual PIECE PIECE { get; set; }
        public virtual TEST TEST { get; set; }
    }
}
