//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiteSPPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT
    {
        public PRODUIT()
        {
            this.ECHANTILLONs = new HashSet<ECHANTILLON>();
        }
    
        public int Identifiant { get; set; }
        public string PositionGD { get; set; }
        public string PositionAVAR { get; set; }
        public Nullable<int> IdentifiantPiece { get; set; }
        public Nullable<int> IdentifiantPeinture { get; set; }
    
        public virtual ICollection<ECHANTILLON> ECHANTILLONs { get; set; }
        public virtual PEINTURE PEINTURE { get; set; }
        public virtual PIECE PIECE { get; set; }
    }
}
