//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiteSPPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTAT_TEST
    {
        public int Identifiant { get; set; }
        public Nullable<bool> Valeur { get; set; }
        public Nullable<int> IdentifiantEchantillon { get; set; }
        public Nullable<int> IdentifiantTest { get; set; }
    
        public virtual ECHANTILLON ECHANTILLON { get; set; }
        public virtual TEST TEST { get; set; }
    }
}
