//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiteSPPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE
    {
        public TYPE()
        {
            this.PIECEs = new HashSet<PIECE>();
        }
    
        public int Identifiant { get; set; }
        public string Type1 { get; set; }
        public Nullable<int> IdentifiantCategorie { get; set; }
    
        public virtual CATEGORIE CATEGORIE { get; set; }
        public virtual ICollection<PIECE> PIECEs { get; set; }
    }
}
