//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualiteSPPP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULE
    {
        public VEHICULE()
        {
            this.PIECEs = new HashSet<PIECE>();
        }
    
        public int Identifiant { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> IdentifiantConstructeur { get; set; }
    
        public virtual CONSTRUCTEUR CONSTRUCTEUR { get; set; }
        public virtual ICollection<PIECE> PIECEs { get; set; }
    }
}
